# Generated by Django 5.0.14 on 2026-07-14 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('won_leads', models.PositiveIntegerField(default=0)),
                ('lost_leads', models.PositiveIntegerField(default=0)),
                ('open_leads', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('won_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('conversions', models.JSONField(blank=True, default=dict)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
