# Generated by Django 5.0.14 on 2026-08-07 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('change_summary', models.CharField(blank=True, default='Initial version', max_length=255)),
                ('created_by_role', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], default='freelancer', max_length=20)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'abstract': False,
            },
        ),
    ]
