# Generated by Django 5.0.14 on 2026-08-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalversion',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
