# Generated by Django 5.0.14 on 2026-08-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposalversion_created_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='target_project_name',
            field=models.CharField(blank=True, default='', help_text='Workspace project title created upon proposal acceptance.', max_length=255),
        ),
    ]
