# Generated by Django 5.0.14 on 2026-08-10 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_target_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of task title strings')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='proposals.proposal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
