# Generated by Django 5.0.14 on 2026-08-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_portal_password_protected_and_more'),
        ('proposals', '0006_proposalmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='clients.client'),
        ),
    ]
