# Generated by Django 5.0.14 on 2026-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='addons',
            field=models.JSONField(blank=True, default=list, help_text='Optional add-ons list: [{id, title, description, amount, is_selected}]'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_feedback',
            field=models.TextField(blank=True, default='', help_text='Revision notes provided by client when requesting changes.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='signed_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='signed_ip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='signed_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='signed_user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
