# Generated by Django 5.0.14 on 2026-08-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.milestone'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_SIGNOFF', 'Ready for Sign-off'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
