services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      POSTGRES_HOST: db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      POSTGRES_HOST: db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      POSTGRES_HOST: db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-winlance}
      POSTGRES_USER: ${POSTGRES_USER:-winlance}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-winlance}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-winlance} -d ${POSTGRES_DB:-winlance}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
