# Generated by Django 5.0.14 on 2026-07-14 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_indexes'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guidance_type', models.CharField(choices=[('PRICING', 'Pricing'), ('NEGOTIATION', 'Negotiation'), ('FOLLOW_UP', 'Follow-up'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('prompt', models.TextField(blank=True, default='')),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('advice', models.TextField(blank=True, default='')),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_sessions', to='leads.lead')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_sessions', to='proposals.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
