# Generated by Django 5.0.14 on 2026-08-08 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_industry_client_location_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_portal_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_passcode',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
