from django.db import transaction
from django.utils import timezone
from rest_framework.exceptions import ValidationError

from apps.proposals.services import render_template

from .models import Contract, ContractTemplate

DEFAULT_CONTRACT_BODY = """# Service Agreement: {{title}}

Date: {{today}}

This agreement is between {{freelancer_name}} ("Freelancer") and {{client_name}}
of {{company}} ("Client").

## Scope
{{proposal_summary}}

## Compensation
Client agrees to pay {{amount}} {{currency}} for the services described above.

## Acceptance
By signing, both parties agree to the terms in this contract.
"""


def build_contract_context(contract):
    proposal = contract.proposal
    lead = contract.lead or (proposal.lead if proposal else None)
    company_name = "Client"
    client_name = contract.user.get_full_name() or contract.user.username
    proposal_summary = ""

    if proposal:
        proposal_summary = proposal.summary or proposal.body[:500]
        if not contract.amount and proposal.amount:
            pass

    if lead:
        if lead.company_id:
            company_name = lead.company.name
        contact = lead.contacts.order_by("created_at").first()
        if contact:
            client_name = f"{contact.first_name} {contact.last_name}".strip() or client_name

    return {
        "title": contract.title,
        "amount": contract.amount,
        "currency": contract.currency,
        "company": company_name,
        "client_name": client_name,
        "freelancer_name": contract.user.get_full_name() or contract.user.username,
        "proposal_summary": proposal_summary or contract.title,
        "today": timezone.now().date().isoformat(),
    }


def ensure_default_contract_template(user):
    template = ContractTemplate.objects.filter(user=user, is_default=True).first()
    if template:
        return template
    return ContractTemplate.objects.create(
        user=user,
        name="Standard contract",
        description="Default Winlance contract template",
        body_template=DEFAULT_CONTRACT_BODY,
        is_default=True,
    )


def create_contract_from_proposal(user, proposal, *, title=None, template=None):
    if proposal.user_id != user.id:
        raise ValidationError({"proposal": "Proposal not found or not owned by you."})

    template = template or ensure_default_contract_template(user)
    return Contract.objects.create(
        user=user,
        proposal=proposal,
        lead=proposal.lead,
        project_id=proposal.project_id,
        template=template,
        title=title or f"Contract: {proposal.title}",
        amount=proposal.amount,
        currency=proposal.currency,
        status=Contract.Status.DRAFT,
    )


def queue_contract_generation(contract):
    from django.conf import settings

    from .tasks import generate_contract_draft

    contract.status = Contract.Status.GENERATING
    contract.save(update_fields=["status", "updated_at"])

    if getattr(settings, "CELERY_TASK_ALWAYS_EAGER", False):
        generate_contract_content(contract)
        return contract

    def enqueue():
        result = generate_contract_draft.delay(str(contract.id))
        Contract.objects.filter(id=contract.id).update(generation_task_id=result.id or "")

    transaction.on_commit(enqueue)
    return contract


def generate_contract_content(contract):
    template_text = (
        contract.template.body_template
        if contract.template_id
        else ensure_default_contract_template(contract.user).body_template
    )
    context = build_contract_context(contract)
    contract.body = render_template(template_text, context)
    contract.status = Contract.Status.READY
    contract.save(update_fields=["body", "status", "updated_at"])
    return contract


def queue_contract_export(contract):
    from django.conf import settings

    from .tasks import export_contract_document

    if getattr(settings, "CELERY_TASK_ALWAYS_EAGER", False):
        build_contract_export(contract)
        return contract

    def enqueue():
        result = export_contract_document.delay(str(contract.id))
        Contract.objects.filter(id=contract.id).update(export_task_id=result.id or "")

    transaction.on_commit(enqueue)
    return contract


def build_contract_export(contract):
    if not contract.body:
        generate_contract_content(contract)
        contract.refresh_from_db()

    export = (
        f"{contract.title}\n"
        f"{'=' * len(contract.title)}\n\n"
        f"{contract.body}\n\n"
        f"---\nGenerated by Winlance on {timezone.now().isoformat()}\n"
    )
    contract.export_content = export
    contract.save(update_fields=["export_content", "updated_at"])
    return contract


def mark_contract_sent(contract):
    if contract.status not in {Contract.Status.READY, Contract.Status.SENT}:
        raise ValidationError({"status": "Contract must be READY before sending."})
    contract.status = Contract.Status.SENT
    contract.save(update_fields=["status", "updated_at"])
    return contract


def mark_contract_signed(contract):
    if contract.status not in {Contract.Status.READY, Contract.Status.SENT}:
        raise ValidationError({"status": "Contract must be READY or SENT before signing."})
    contract.status = Contract.Status.SIGNED
    contract.signed_at = timezone.now()
    contract.save(update_fields=["status", "signed_at", "updated_at"])
    return contract
