# Generated by Django 5.0.14 on 2026-08-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
